"""refactor calendar table

Revision ID: 90d06ac3a65a
Revises: abd2c583611f
Create Date: 2024-02-24 16:28:45.614203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d06ac3a65a'
down_revision: Union[str, None] = 'abd2c583611f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendars', sa.Column('city', sa.String(), nullable=True))
    op.add_column('calendars', sa.Column('state', sa.String(), nullable=True))
    op.drop_constraint('calendars_name_key', 'calendars', type_='unique')
    op.drop_column('calendars', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendars', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('calendars_name_key', 'calendars', ['name'])
    op.drop_column('calendars', 'state')
    op.drop_column('calendars', 'city')
    # ### end Alembic commands ###
