"""remove unnecessary days_off_table

Revision ID: abd2c583611f
Revises: eec3dd028740
Create Date: 2024-02-24 16:16:28.382992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd2c583611f'
down_revision: Union[str, None] = 'eec3dd028740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_off_table')
    op.drop_constraint('calendars_work_schedule_id_fkey', 'calendars', type_='foreignkey')
    op.drop_column('calendars', 'work_schedule_id')
    op.add_column('work_schedules', sa.Column('calendar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'work_schedules', 'calendars', ['calendar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_schedules', type_='foreignkey')
    op.drop_column('work_schedules', 'calendar_id')
    op.add_column('calendars', sa.Column('work_schedule_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('calendars_work_schedule_id_fkey', 'calendars', 'work_schedules', ['work_schedule_id'], ['id'])
    op.create_table('days_off_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('calendar_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name='days_off_table_calendar_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='days_off_table_pkey')
    )
    # ### end Alembic commands ###
